[package]
name = "genco"
version = "0.5.0-alpha.3"
authors = ["John-John Tedro <udoprog@tedro.se>"]
license = "MIT/Apache-2.0"
edition = "2018"
readme = "README.md"
repository = "https://github.com/udoprog/genco"
homepage = "https://github.com/udoprog/genco"
documentation = "https://docs.rs/genco"
description = """
Even simpler code generation for Rust.
"""

[dependencies]
genco-derive = {path = "genco-derive", version = "=0.5.0-alpha.3"}

[dev-dependencies]
anyhow = "1.0.31"