[package]
name = "genco"
version = "0.10.2"
authors = ["John-John Tedro <udoprog@tedro.se>"]
license = "MIT/Apache-2.0"
edition = "2018"
readme = "README.md"
repository = "https://github.com/udoprog/genco"
homepage = "https://github.com/udoprog/genco"
documentation = "https://docs.rs/genco"
description = """
Genco, the even simpler code generator for Rust.
"""

[dependencies]
genco-macros = {path = "genco-macros", version = "0.10.2"}
relative-path = "1.2.0"
smallvec = "1.4.0"

[dev-dependencies]
anyhow = "1.0.31"
rand = "0.7.3"
