[package]
name = "genco"
version = "0.3.11"
authors = ["John-John Tedro <udoprog@tedro.se>"]
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/udoprog/genco"
homepage = "https://github.com/udoprog/genco"
documentation = "https://docs.rs/genco"
description = """
Even simpler code generation for Rust.
"""

[dependencies]
serde = {version = "1.0"}
serde_derive = {version = "1.0"}
