[package]
name = "genco-macros"
version = "0.8.0"
authors = ["John-John Tedro <udoprog@tedro.se>"]
license = "MIT/Apache-2.0"
edition = "2018"
repository = "https://github.com/udoprog/genco"
homepage = "https://github.com/udoprog/genco"
documentation = "https://docs.rs/genco"
description = """
Macros used by Genco, the even simpler code generator for Rust.
"""

[dependencies]
syn = { version = "1.0.31", features = ["full"] }
quote = "1.0.3"
proc-macro2 = { version = "1.0.10", features = ["span-locations"] }

[dev-dependencies]
genco = { path = "..", version = "0.8.0" }

[lib]
proc-macro = true