name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
    - run: cargo +nightly test --all --workspace
      env:
        RUSTFLAGS: --cfg genco_nightly
